### ISSUE TITLE
File not found error best.pt (my own weights file for custom data)

### ISSUE THREAD

**Issue by PRASANNA-416** [35grain/label-studio-yolov8-backend#3]
While running docker-compose up --build. It say best.pt file not found. under which directory i should put this file ?

The above erro I got when I put the best.pt file in root directory

**Comment by 35grain** [comment]
Hey! It should work if you add the `best.pt` trained model weights into the same directory with `model.py`. I have now also updated the readme accordingly as I had previously included my project-specific weights and have removed them. If you got the error by running docker-compose without the `best.pt` file first, you might need to delete the built Docker image and try again, as otherwise it will not include the changes.
